env:
  browser: true
  es2020: true
extends:
  - 'airbnb-base'
parserOptions:
  ecmaVersion: latest
rules:
  indent: off
  no-tabs: off
  import/extensions: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  no-console: 0